### ISSUE TITLE
Not working for Firefox 71 on Linux

### ISSUE THREAD

**Issue by clichte** [NeApp/neon-extension#36] opened 2019-12-05 00:08 UTC
I'm on Void Linux which just updated Firefox to version 71.  When listening to music on Google Play Music, it no longer scrobbles to Last.fm.

**Comment by Eagle3386** [comment] 2020-02-27 12:52
Probably a duplicate of #35.

**Comment by fuzeman** [comment] 2020-03-20 04:08
Everything should be working again in [v2.3.1](https://github.com/RadonApp/radon-extension/releases/tag/v2.3.1).

**Closed as completed by fuzeman** 2020-03-20 04:08 UTC
